name : testin cd playwright e2e
on:
  workflow_dispatch:

jobs:
  testingjob:
    runs-on: ubuntu-latest
    steps:
      - name: fetching the code
        uses: actions/checkout@master
        
      - name: Run integration tests
        uses: matt-ball/newman-action@master
        with:
          collection: api-testcollection-devops.postman_collection.json
          reporters: '["junit"]'
          reporter: '{"junit":{"export":"newman-report.xml"}}'


        #gebruik geen npm init playwright@latest maar npm ci want het zit al in de nodemodules
      - name: Run end-to-end tests
        run: |
          npm ci
          npx playwright install --with-deps
          npx playwright test

      - name: Upload Playwright HTML report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/
          
      - name: Archive test reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: |
            newman-report.xml
            playwright-report/


