name: test deployment
on:
  workflow_dispatch:

jobs:
  firstjob:
    runs-on: self-hosted
    steps:
      - name: docker pull image
        run: docker pull lahcen225/calculator-app:latest
      - name: stop any running container
        run: docker stop $(docker ps -q)
      - name: run docker container
        run: docker run -d  -p 3000:8080 --name calculater-app lahcen225/calculator-app:latest
        
